version: "3.8"
services:
  mongodb:
    image: mongo:6.0.4
    container_name: studentdb-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: studentdb
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
    driver: local